name: test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04']
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          clangFormatVersion: 11
          source: './src'
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install -y autoconf autoconf-archive automake make g++ libprotoc-dev
      - run: aclocal
      - run: automake --add-missing
      - run: autoconf
      - run: ./configure
      - run: make
      - run: ./src/protoxs --version
      - run: make dist
      - uses: actions/upload-artifact@v2
        with:
          path: protobuf-perlxs-*.tar.gz
